apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: INSERT_BEFORE # INSERT_FIRST added on istio v1.5
      value:
        name: envoy.ext_authz
        config:
          httpService:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: cookie
                - exact: X-Auth-Token
            authorizationResponse:
              allowedUpstreamHeaders:
                patterns:
                - exact: kubeflow-userid
            serverUri:
              cluster: outbound|8080||authservice.istio-system.svc.cluster.local
              failureModeAllow: false
              timeout: 10s
              uri: http://authservice.istio-system.svc.cluster.local
          statusOnError:
            code: GatewayTimeout
